apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
bases:
  - ../../../projects/devops/build
  - ../../../projects/devops/jenkins
  - ../../../projects/devops/nexus2
  - ../../../projects/devops/sonarqube
resources:
  - quay-cicd-sealedsecret.json
  - quay-creds-sealedsecret.json
